# Generated by Django 5.1.6 on 2025-03-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(default='default_user/def_user.jpg', upload_to='profile/'),
        ),
    ]
