# Generated by Django 5.1.6 on 2025-03-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_category',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Internship', 'Internship')], default='Employee', max_length=50),
        ),
    ]
