# Generated by Django 5.1.6 on 2025-03-24 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile_user_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nich_name',
        ),
    ]
