# Generated by Django 5.1.6 on 2025-03-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='mail',
            name='subject',
            field=models.CharField(default='No Subject', max_length=1000),
            preserve_default=False,
        ),
    ]
