# Generated by Django 5.1.6 on 2025-04-07 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_mail_files_mail_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveDatasM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savemail_data', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=1000)),
                ('text', models.CharField(max_length=5000)),
                ('files', models.FileField(blank=True, null=True, upload_to='pdf/')),
                ('text_time', models.DateField(default=django.utils.timezone.now)),
                ('names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
