# Generated by Django 5.1.6 on 2025-04-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_companycodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycodemodel',
            name='user_pass',
            field=models.CharField(default='companyOffice', max_length=400),
        ),
    ]
