# Generated by Django 5.1.6 on 2025-04-10 07:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_companycodemodel_user_pass'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CGM_Image', models.ImageField(default='default_user/def_user.jpg', upload_to='CGM/')),
                ('CGM_Name', models.CharField(max_length=100)),
                ('CGM_Category', models.CharField(max_length=100)),
                ('CGM_Description', models.CharField(blank=True, default='Group Chat, Description!', max_length=5000, null=True)),
                ('CGM_Slogon', models.CharField(default='Welcome To New Group!', max_length=500)),
                ('CGM_Time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CGChartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CGC_UserName', models.CharField(max_length=300)),
                ('CGC_Text', models.CharField(blank=True, max_length=7000, null=True)),
                ('CGC_Image', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('CGC_File', models.FileField(blank=True, null=True, upload_to='File/')),
                ('CGC_Video', models.FileField(blank=True, null=True, upload_to='Video/')),
                ('CGC_Time', models.DateField(default=django.utils.timezone.now)),
                ('CGC_ChatLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categorygroupmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UserOfCGM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UOC_Id', models.CharField(max_length=100)),
                ('UOC_username', models.CharField(max_length=300)),
                ('UOC_Time', models.DateField(default=django.utils.timezone.now)),
                ('UOC_Category', models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], default='Member', max_length=50)),
                ('UOC_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categorygroupmodel')),
            ],
        ),
    ]
