# Generated by Django 5.1.6 on 2025-04-12 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_categorygroupmodel_cgchartmodel_userofcgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='cgchartmodel',
            name='CGC_Times',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
