# Generated by Django 5.1.6 on 2025-04-12 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_cgchartmodel_cgc_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cgchartmodel',
            name='CGC_Times',
        ),
        migrations.AddField(
            model_name='cgchartmodel',
            name='CGC_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cgchartmodel',
            name='CGC_Time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
