# Generated by Django 5.1.6 on 2025-04-13 07:34

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_cgchartmodel_cgc_times_cgchartmodel_cgc_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cgchartmodel',
            name='CGC_Time',
            field=models.TimeField(default=home.models.get_current_ist_time),
        ),
    ]
